/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dbe1ff",
        "tertiary-container": "#3cb58b",
        error: "#ffb4ab",
        tertiary: "#67dbaf",
        secondary: "#ffb873",
        "surface-container": "#1e1f25",
        "inverse-primary": "#3459b5",
        "primary-fixed-dim": "#b3c5ff",
        "secondary-fixed": "#ffdcbf",
        "on-primary-fixed-variant": "#13409c",
        "on-tertiary-container": "#00412e",
        "surface-bright": "#38393f",
        "outline-variant": "rgba(255, 255, 255, 0.1)",
        "on-secondary-fixed-variant": "#6a3b00",
        "tertiary-fixed": "#84f8ca",
        "on-primary-fixed": "#00184a",
        "on-secondary-container": "#ffc187",
        background: "transparent",
        "on-tertiary-fixed": "#002115",
        "on-background": "#1d1d1f",
        "on-surface-variant": "#4a4a4f",
        "on-secondary-fixed": "#2d1600",
        "surface-container-highest": "#33343b",
        "surface-dim": "transparent",
        "error-container": "#93000a",
        "primary-container": "#ffffff",
        outline: "rgba(255, 255, 255, 0.2)",
        "on-primary-container": "#000000",
        "on-primary": "#000000",
        "on-tertiary": "#003827",
        "on-secondary": "#4b2800",
        "on-error-container": "#ffdad6",
        surface: "transparent",
        "inverse-on-surface": "#2f3036",
        "tertiary-fixed-dim": "#67dbaf",
        "on-tertiary-fixed-variant": "#00513a",
        "surface-tint": "#b3c5ff",
        "surface-container-low": "#1a1b21",
        "surface-container-high": "#282a30",
        "inverse-surface": "#e2e2ea",
        "secondary-container": "#824900",
        "secondary-fixed-dim": "#ffb873",
        "surface-container-lowest": "#0c0e14",
        "on-error": "#690005",
        primary: "#ffffff",
        "on-surface": "#1d1d1f",
        "surface-variant": "rgba(255, 255, 255, 0.05)",
        "admin-rose": "#F26B6B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "48px",
        "container-max": "1280px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        "label-sm": ["IBM Plex Mono"],
        "headline-lg-mobile": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "body-lg": ["IBM Plex Sans"],
        "body-md": ["IBM Plex Sans"],
        "headline-md": ["Space Grotesk"],
        "data-mono": ["IBM Plex Mono"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
